- name: make server dir
  file: path={{ sources_dir }} state=directory owner={{ http_user }} group={{ http_group }}
  sudo: yes

- name: checkout
  git: repo=https://github.com/quark-tekliner/sphericalcow.git dest={{ sources_dir }}
  notify:
    - build static
    - update bower components

- name: install packages
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - libtool
  sudo: yes

- name: compile binary dependencies
  shell: ./autogen.sh && ./configure --prefix={{ sources_dir }}vendor && make install chdir={{ sources_dir }}vendor/nanomsg

- name: install python requirements
  pip: virtualenv={{ sources_dir }} requirements={{ sources_dir }}requirements.txt
  pip: virtualenv={{ sources_dir }} name=https://github.com/tonysimpson/nanomsg-python/archive/1.0.tar.gz

- name: install nodejs requirements
  npm: path={{ sources_dir }}src/web

- name: configure nginx
  template: src="nginx.j2" dest="/etc/nginx/sites-enabled/sphericalcow.mobi"
  sudo: yes
  notify:
    - restart nginx

- name: configure upstart
  template: src="upstart.j2" dest="/etc/init/sphericalcow.conf"
  sudo: yes
  notify:
    - restart sphericalcow